apiVersion: v1
kind: Namespace

metadata:
  name: nephio

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition

metadata:
  name: data-plane
  namespace: nephio
  labels:
    app.kubernetes.io/name: nephio
    app.kubernetes.io/component: demo

spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "data-plane",
      "type": "ptp",
      "ipam": {
        "type": "host-local",
        "subnet": "10.1.1.0/24",
        "routes": [
          { "dst": "10.1.2.0/24", "gw": "10.1.1.1" }
        ]
      }
    }'

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo1
  namespace: nephio
  labels:
    app.kubernetes.io/name: nephio
    app.kubernetes.io/component: demo1

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nephio
      app.kubernetes.io/component: demo1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nephio
        app.kubernetes.io/component: demo1
      annotations:
        k8s.v1.cni.cncf.io/networks: data-plane
    spec:
      containers:
      - name: busybox
        image: docker.io/busybox:1.34.1
        command: [ sleep ]
        args: [ infinity ]

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo2
  namespace: nephio
  labels:
    app.kubernetes.io/name: nephio
    app.kubernetes.io/component: demo2

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nephio
      app.kubernetes.io/component: demo2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nephio
        app.kubernetes.io/component: demo2
      annotations:
        k8s.v1.cni.cncf.io/networks: data-plane
    spec:
      containers:
      - name: busybox
        image: docker.io/busybox:1.34.1
        command: [ sleep ]
        args: [ infinity ]

