kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: edge1
networking:
  apiServerAddress: 192.168.1.11 # lab1
  apiServerPort: 31000
  podSubnet: 10.97.0.0/16
  serviceSubnet: 10.197.0.0/16
nodes:
- role: control-plane
  extraPortMappings:
  # see dashboard-node-port.yaml
  - containerPort: 32000
    hostPort: 32000
